ruby '2.3.3'
source 'https://rubygems.org'
gem 'addressable'
gem 'bci'
gem 'dotenv'
gem 'facebook-messenger', github: 'hyperoslo/facebook-messenger'
gem 'haversine'
gem 'httparty'
gem 'puma'
gem 'sinatra'
gem 'sucker_punch', '~> 2.0'
